version: '3'

services: 
  emails:
    build: ./
    depends_on: 
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password